---
# tasks file for nginx_role
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present
    
- name: Config Nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/nginx.conf
    mode: 0644
  notify:
    - Restart Nginx

- name: Linking new site
  become: yes
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
    state: link

