---
# handlers file for wordpress
    - name: Reload Apache
      service:
        name: nginx
        state: reloaded

    - name: Restart Apache
      service:
        name: nginx
        state: restarted
