---
# tasks file for mysql
# install mysql
- name: Install MySQL
  become: yes
  apt:
    name={{ item }} state=present
  loop: [ 'mysql-server', 'python3-pymysql' ] 

- name: Set the root password
  become: yes
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}" 
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
 
- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

# tasks file for mysql
#  name: Create mysql database
#  become: yes
#  mysql_db: name=wordpress state=present

#- name: Create mysql user
#  become: yes
#  mysql_user:
#    name=oleg
#    password=oleg1998
#    priv=*.*:ALL
